-- vim.cmd('source ~/.config/nvim/kha.plugins')
-- vim.cmd('source ~/.config/nvim/kha.nvim')
require('plugins')
require('plugins-settings')
require('appearance')
require('aliases')
require('keymappings')
require('denite')
require('funcs')
require('lsp')
